---
# https://github.com/Genymobile/scrcpy/blob/master/doc/linux.md

- name: Enable Copr
  become: true
  community.general.copr:
    state: enabled
    name: zeno/scrcpy

- name: Install Scrcpy
  become: true
  ansible.builtin.dnf:
    name:
      - scrcpy
    state: latest